services:
  postgres:
    image: postgres
    container_name: postgres-test
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  pg-backup:
    build:
      context: .
      dockerfile: Dockerfile.pg-backup
    container_name: postgres-backup
    depends_on:
      - postgres
    environment:
      PGHOST: postgres
      PGUSER: admin
      PGPASSWORD: admin
      PGPORT: 5432
      TZ: "Europe/Moscow"
      CRON_SCHEDULE: "* 3 * * *"  # testing (every minute) "*/1 * * * *".
    volumes:
      - ./backups:/backups

volumes:
  db:
