FROM postgres
RUN apt-get update \
    && apt-get install -y --no-install-recommends cron \
    && rm -rf /var/lib/apt/lists/*
COPY scripts/backup_entrypoint.sh /usr/local/bin/backup_entrypoint.sh
RUN chmod +x /usr/local/bin/backup_entrypoint.sh || true

ENV CRON_SCHEDULE="* 3 * * *"
ENTRYPOINT ["/bin/sh","/usr/local/bin/backup_entrypoint.sh"]
